config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  get 'login/index', to: 'login#index', as: 'login_index'

  get 'index', to: 'index#index', as: 'index'

  root "login#index"

  get 'staff', to: 'staff#index', as: 'staff_index'

  resources :students
  get '/student', to: "students#index", as: 'userStudent'

  get "logout", to: "login#destroy", as: 'logout'

  resources :classes

  get 'list', to: "classes#list", as: 'list'

  get 'show', to: "classes#show", as: 'show'

  # get 'edit', to: "classes#edit", as: 'edit'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_times.rb
class ClassTimes < ApplicationRecord
end

app/models/classes.rb
class Classes < ApplicationRecord
  has_rich_text :content
  has_many :versions, as: :item, dependent: :destroy

  validates :class_name, presence: true
  validates :class_code, presence: true, :uniqueness => true
end

app/models/staff.rb
class Staff < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :staff_id, presence: true, :uniqueness => true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :student_id, presence: true, :uniqueness => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/version.rb
class Version < ApplicationRecord
  #belongs_to :staff
  belongs_to :item, polymorphic: true
  has_rich_text :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController

  def list
    @user = Staff.find_by(staff_id: session[:id])
    @classes = Classes.all()
  end

  def show
    @user = Staff.find_by(staff_id: session[:id])
    @course = Classes.find_by(id: params[:format])
    @class_times = ClassTimes.where(class_code: @course.class_code)
    @classes = Classes.find_by(id: params[:format])
  end

  def update
    @user = Staff.find_by(staff_id: session[:id])
    @classes = Classes.find(params[:id])
    if @classes.update(classes_params)
      redirect_to list_path
    else
      render 'edit'
    end
  end

  def classes_params
    params.require(:classes).permit(:class_name, :class_code, :teacher_name, :description, :content)
  end
  # def edit
  #   if course[:user_id]
  #     @user = User.find_by(id: session[:user_id])
  #   end
  #   @course = Course.find(params[:id])
  # end
  #
  def edit
    @user = Staff.find_by(staff_id: session[:id])

    @classes= Classes.find(params[:id])

  end

  def new
    @user = Staff.find_by(staff_id: session[:id])

    @classes = Classes.new
  end


end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @user = Student.find_by(student_id: session[:id])
    end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    if params[:id] != nil
      session[:id] = params[:id]
    end

    id = session[:id]

    if Student.exists?(student_id: id) #&& Student.password == params[:password]
      redirect_to index_path(id), notice: "Logged in successfully"

    elsif Staff.exists?(staff_id: id)
      redirect_to staff_index_path(id)
    # else
    #   flash[:alert] = "invalid ID or password"
    end
  end

  def destroy
    session.clear
    redirect_to login_index_path
  end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  def index
    @user = Staff.find_by(staff_id: session[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    #do not delete below
    @user = Staff.find_by(staff_id: session[:id])

    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    #do not delete below
    @user = Staff.find_by(staff_id: session[:id])
  end

  # GET /students/new
  def new
    #do not delete below
    @user = Staff.find_by(staff_id: session[:id])
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    #do not delete below
    @user = Staff.find_by(staff_id: session[:id])
  end

  # POST /students
  # POST /students.json
  def create

    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to index_path, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    #do not delete below
    @user = Staff.find_by(staff_id: session[:id])
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:student_id, :first_name, :last_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/classes/_form.html.erb
<%= form_with(model: classes, local: true) do |form| %>
  <%# if classes.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(classes.errors.count, "error") %> prohibited this class from being saved:</h2>-->

<!--      <ul>-->
        <%# classes.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

  <div class="field">
    <%= form.label :class_name %>
    <%= form.text_field :class_name%>
  </div>

  <div class="field">
    <%= form.label :class_code %>
    <%= form.text_field :class_code %>
  </div>

  <div class="field">
    <%= form.label :teacher_name %>
    <%= form.text_field :teacher_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classes/edit.html.erb
<%= stylesheet_link_tag "classes.css" %>

<%= render 'form', classes: @classes %>

app/views/classes/list.html.erb
<h1>Classes</h1>

<table class="ui table">
  <thead>
  <tr>
    <th>Class Code</th>
    <th>Class Name</th>
    <th>Professor</th>
    <th>Description</th>
    <th class="right aligned"></th>
  </tr>
  </thead>

  <tbody>
  <% @classes.each do |classs| %>
    <tr>
    <td><%= classs.class_code %></td>
    <td><%= classs.class_name %></td>
    <td><%= classs.teacher_name %></td>
    <td><%= classs.description %></td>
      <td class="right aligned">
        <div class="ui small basic buttons">
          <%= link_to show_path(classs), class: "ui button" do %>
            <i class="eye icon"></i> Show
          <% end %>
          <%= link_to edit_class_path(classs), class: "ui button" do %>
            <i class="eye icon"></i> Edit
          <% end %>


        </div>
      </td>
  <% end %>
  </tr>
    </tbody>
</table>

app/views/classes/show.html.erb
<%= stylesheet_link_tag "classes.css" %>

<h1>
  <%= @course.class_code %> <%= @course.class_name %>
</h1>
<table class="ui table">
  <tbody>
    <tr>
      <td class="row_header">Career: </td>
      <td><%= @course.career %></td>
    <tr>
      <td class="row_header">Units: </td>
      <td><%= @course.units %></td>
    </tr>
    <tr>
      <td class="row_header">Term: </td>
      <td><%= @course.term %></td>
    </tr>
    <tr>
      <td class="row_header">Course Coordinator: </td>
      <td><%= @course.teacher_name %></td>
    </tr>
    <tr>
      <td class="row_header">Campus: </td>
      <td><%= @course.campus %></td>
    </tr>
    <tr>
      <td class="row_header">Contact: </td>
      <td>Up to <%= @course.contact %> hours per week</td>
    </tr>
    <tr>
      <td class="row_header">Pre-Requisite: </td>
      <td><%= @course.pre_requisite %></td>
    </tr>
    <tr>
      <td class="row_header">Incompatible:	 </td>
      <td><%= @course.incompatible %></td>
    </tr>
    <tr>
      <td class="row_header">Course Description:	 </td>
      <td><%= @course.description %></td>
    </tr>
    <tr>
      <td class="row_header">Course Content</td>
      <td><%= @classes.content %></td>
    </tr>
  </tbody>
</table>

<h2>Class Times</h2>

<table class="ui table">
  <thead>
  <tr>
    <th>Class Type </th>
    <th>Day </th>
    <th>Class Times </th>
    <th>Location </th>
    <th>Class Size </th>
  </tr>
  </thead>
  <% @class_times.each do |times| %>
    <tr>
      <td><%= times.class_type %></td>
      <td><%= times.day %></td>
      <td><%= times.start_time %> to <%= times.end_time %></td>
      <td><%= times.location %></td>
      <td><%= times.class_size %></td>
    </tr>
  <% end %>
</table>


  <h2>
    Versions
    <%= @classes.versions.size %>
  </h2>

  <table class='table'>
    <thead>
    <tr>
      <th>ID</th>
      <th>Previous Content</th>
    </tr>
    </thead>

    <tbody>
    <% @classes.versions.order(id: :desc).each do |version| %>
      <tr>
        <td><%= version.id %></td>
        <td><%= version.content %></td>
      </tr>
    <% end %>
    </tbody>

</table>

app/views/index/index.html.erb
<div class="index">
  YOU ARE Student
</div>

<div class ="index">
  Search for a Course
  <%#= form_with(url: "/course", method: :get, local:true) do %>

<!--    <div class="input-field">-->
      <%#= label_tag(:name, "Search for Course") %>
      <%#= text_field_tag(:name, nil, value: name, class: "login-box") %>
<!--    </div>-->
    <%#= submit_tag("Search", class: "Search") %>
  <%# end %>
</div>

<div class="index">
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
  Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec,
  pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate
  eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.
  Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu,
  consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus
  varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
  Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum.
  Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus.
  Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt.
  Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.
  Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,
</div>

<br>
<div class="logout">
  <%=link_to "Logout",logout_path, class: "login-box" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseCatalogueEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="topbar">
    <%= image_tag("uoa-logo.png", :alt => "UOA logo") %>
  </div>



<!--  <p class="notice"><%#= notice %></p>-->
<!--  <p class="alert"><%#= alert %></p>-->

  <%#= render partial: "shared/navbar" %>

  <% unless current_page?(login_index_path) or current_page?('/') or current_page?(new_student_path)%>
    <%= render partial: "shared/navbar-staff" %>
  <% end %>
  <div class="content">

    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/login/index.html.erb
<div class="index">
  <h1>Course Catalogue Editor</h1>

  <%= form_with(url: "/login/index", method: :get, local:true) do %>

    <div class="mb-3">
      <%= label_tag(:id, "Username:") %>
      <%= text_field_tag(:id, nil, value: session[:id], class: "login-box") %>

      <%= label_tag(:password, "Password:") %>
      <%= password_field_tag(:password, nil, class: "login-box") %>
    </div>

    <%= submit_tag("Login", class: "login") %>
    <%=link_to "Register", new_student_path, class: "login" %>
  <% end %>

</div>

app/views/shared/_navbar-staff.html.erb
<nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">Adelaide University</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if @user.user_type == 0 %>
        <%= link_to "Home", index_path, class: "nav-item nav-link active" %>
      <% elsif @user.user_type == 1 %>
        <%= link_to "Home", staff_index_path, class: "nav-item nav-link active" %>
      <% elsif@user.user_type == 2 %>
        <%= link_to "Home", staff_index_path, class: "nav-item nav-link active" %>
      <%end %>
      <% if @user.user_type == 2 %>
      <%= link_to "View Students", students_path, class: "nav-item nav-link active" %>
      <%end %>
    </div>

    </div>
  </div>
  <div class="topnav-right">
    <% if @user %>
      logged in as <%= @user.first_name %>
      <%= link_to "Logout", logout_path, class: "nav-item nav-link" %>
    <% end %>
</nav>

app/views/shared/_navbar-student.html.erb
<nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="index">Adelaide University</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Features</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#">Disabled</a>
    </div>
  </div>
</nav>

app/views/staff/index.html.erb
<div class="index">
  Welcome Staff!

  <div class="login-details">
  <%= @user.first_name %>
  <%= @user.last_name %>
    <%= @user.staff_id %>
    <%= @user.user_type %>

  </div>
  Welcome to the Course Catalogue Editor!
  <div>
    <%=link_to "View Courses", list_path %>
  </div>

</div>

<br>
<div class="logout">
  <%=link_to "Logout",logout_path, class: "login-box" %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Student ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.student_id %></td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
<br>
<br>
<br>
<%= button_to 'Logout', '/', method: :get %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', login_index_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student ID:</strong>
  <%= @student.student_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>